import Zeal.Certificates.NumericalChecker

/-! Generated by `scripts/CertGen.lean` from a certificate JSON; do not edit by hand. -/

open Zeal.Certificates

def exampleLP_P : LPData := ⟨2,
  [
    ([
      (0, (1)),
      (1, (1))], (3/2)),
    ([
      (0, (1)),
      (1, (-1))], (1/3))],
  [
      (0, (1)),
      (1, (1))],
  [
    (0),
    (0)],
  [
    (1),
    (1)]⟩

def exampleLP_C : LPCert := ⟨[
    (1),
    (0)],
  [
    (0),
    (0)],
  [
    (0),
    (0)],
  (3/2)⟩

/-- C6.1: the certificate passes the checker (kernel evaluation). -/
theorem exampleLP_checked : checkLP exampleLP_P exampleLP_C = true := by decide +kernel

/-- C6.1 soundness: the certified bound holds at every real feasible point. -/
theorem exampleLP_bound (x : ℕ → ℝ) (hx : exampleLP_P.Feasible x) :
    rowEval exampleLP_P.obj x ≤ ((exampleLP_C.bound : ℚ) : ℝ) :=
  checkLP_sound exampleLP_checked hx

#print axioms exampleLP_bound
