import Zeal.Certificates.NumericalChecker

/-! Generated by `scripts/CertGen.lean` from a certificate JSON; do not edit by hand. -/

open Zeal.Certificates

def exampleDC_D : DCData := ⟨2,
  [
    (0),
    (0)],
  [
    (1),
    (1)],
  [
    (0, 1, (1/2)),
    (1, 0, (1/3))]⟩

def exampleDC_obj : SparseRow := [
      (0, (1)),
      (1, (1))]

def exampleDC_w : List ℚ := [
    (1),
    (1)]

def exampleDC_C : LPCert := ⟨[
    (0),
    (0)],
  [
    (1),
    (1)],
  [
    (0),
    (0)],
  (2)⟩

/-- C6.2: the witness passes the checker (kernel evaluation). -/
theorem exampleDC_witness : checkWitness exampleDC_D exampleDC_w = true := by decide +kernel

/-- C6.1: the dual certificate passes the checker (kernel evaluation). -/
theorem exampleDC_cert : checkLP (exampleDC_D.toLP exampleDC_obj) exampleDC_C = true := by
  decide +kernel

/-- C6.1 + C6.2: certified bracket over ℝ. -/
theorem exampleDC_bracket :
    exampleDC_D.Feasible (fun j => ((exampleDC_w.getD j 0 : ℚ) : ℝ)) ∧
    rowEval exampleDC_obj (fun j => ((exampleDC_w.getD j 0 : ℚ) : ℝ)) ≤ ((exampleDC_C.bound : ℚ) : ℝ) ∧
    ∀ x : ℕ → ℝ, exampleDC_D.Feasible x → rowEval exampleDC_obj x ≤ ((exampleDC_C.bound : ℚ) : ℝ) :=
  certified_bracket exampleDC_witness exampleDC_cert

#print axioms exampleDC_bracket
