"""mlt_common.py -- shared objects of the ZEAL ML-transfer experiment (exp3_ml).

Declared setup (fixed BEFORE any result was looked at; see findings.md section 1):
  data    : SYNTHETIC hourly electricity-feeder loads, 12 feeders x 30 weeks (5040 h), generated by `make_data(seed=0)`
            (regional temperature: stationary mean + daily cycle + 2-3-day weather fronts (hourly AR(1) phi 0.98, sd 3.5 C); per-feeder residential/
            commercial daily-weekly profile, cooling sensitivity, linear growth, one step change for some feeders,
            AR(1) noise).  Declared synthetic: no public dataset was downloaded.
  task    : peak-risk classifier.  Label at hour t = 1{ max load over (t, t+h] > cap_j }, cap_j = 80th percentile of the
            feeder's training-period maxima over blocks of h hours; h = 24 (models 'mlp', 'feat': next-day risk) or h = 168
            (models 'mlp7', 'feat7': next-week capacity risk).  Input = the past W = 168 hours of the feeder's z-scored load
            (z = (load - mean_j)/sd_j with training-period statistics).  Output f(t) = P(peak in next 24 h).
  models  : 'mlp' = raw-lag MLP 168-64-64-1 ReLU + sigmoid; 'feat' = rolling-feature MLP (fixed linear layer = 10 block means of the
            window, see FEAT.BLOCKS, then 10-32-32-1 ReLU + sigmoid); 'feat24' = day-level feature MLP (6 block means, every block
            >= 24 h, FEAT.BLOCKS24, then 6-32-32-1 ReLU + sigmoid).  (Tried and discarded during set-up, before any ZEAL computation: a GAP
            fully-convolutional classifier (eval AUC 0.53, cannot localise recent hours) and a strided 1-D CNN (AUC 0.75, verifier
            behaviour indistinguishable from 'mlp' in a smoke test); recorded in findings.md.)
  split   : train weeks 1-20, early-stopping weeks 21-24, evaluation = the last 6 weeks (T = 1008 hourly outputs per
            feeder; each output uses the 167 preceding hours as context).
  perturbation (declared feature-uncertainty set): every hourly z-scored load value y_s of the evaluation series
            (T + W - 1 = 1175 values per feeder) may be off by at most eps (l_inf ball on the SERIES, shared by every
            sliding window that contains s).  eps in EPS_GRID (units: training-period standard deviations).
"""
import os as _os, sys as _sys
try:
    from .. import paths                    # imported as part of the package
except ImportError:
    _sys.path.insert(0, _os.path.join(_os.path.dirname(_os.path.abspath(__file__)), "..")); import paths
import os, json, numpy as np, torch, torch.nn as nn

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = paths.EXP3_ML
os.makedirs(OUT, exist_ok=True)
W = 168                    # input window (hours)
T = 1008                   # evaluation outputs per feeder (6 weeks)
N_ENT = 12
H_TOT = 24 * 7 * 30
TRAIN_END = 24 * 7 * 20
VAL_END = 24 * 7 * 24
EVAL_START = H_TOT - T     # first evaluation output hour (output at hour t uses z[t-W+1 .. t])
EPS_GRID = [0.01, 0.02, 0.05, 0.10]
LAGS_DYADIC = [1, 2, 4, 8, 16, 32, 64, 128]
DEV = "cuda" if torch.cuda.is_available() else "cpu"


def make_data(seed=0, horizon=24):
    rng = np.random.default_rng(seed)
    s = np.arange(H_TOT); hour = s % 24; dow = (s // 24) % 7
    # regional temperature (deg C): stationary mean, daily cycle, weather fronts (AR(1) on hours)
    front = np.zeros(H_TOT); e = rng.normal(0, 1, H_TOT)
    for i in range(1, H_TOT):
        front[i] = 0.98 * front[i - 1] + 0.70 * e[i]
    temp = 19 + 5 * np.sin(2 * np.pi * (hour - 9) / 24) + front
    loads, meta = [], []
    for j in range(N_ENT):
        b = rng.uniform(0.8, 1.2); alpha = rng.uniform(0, 1)                     # alpha = commercial share
        res = 0.6 * np.exp(-0.5 * ((hour - 19) / 2.5) ** 2) + 0.25 * np.exp(-0.5 * ((hour - 8) / 1.5) ** 2)
        com = np.exp(-0.5 * ((hour - 13) / 3.5) ** 2) * (dow < 5)
        prof = (1 - alpha) * res + alpha * com
        cool = rng.uniform(0.01, 0.04); growth = rng.uniform(-0.02, 0.02)
        step = np.zeros(H_TOT)
        if rng.random() < 0.5:
            s0 = rng.integers(TRAIN_END // 2, H_TOT - 24 * 7); step[s0:] = rng.uniform(0.02, 0.06)
        noise = np.zeros(H_TOT); en = rng.normal(0, 1, H_TOT); sig = rng.uniform(0.03, 0.05)
        for i in range(1, H_TOT):
            noise[i] = 0.8 * noise[i - 1] + sig * np.sqrt(1 - 0.64) * en[i]
        load = b * (1 + 0.35 * prof + growth * s / H_TOT + step) + b * cool * np.maximum(temp - 20, 0) + b * noise
        loads.append(load); meta.append(dict(base=b, commercial_share=alpha, cooling=cool, growth=growth, step=float(step.max()), noise_sd=sig))
    loads = np.array(loads)
    mu = loads[:, :TRAIN_END].mean(1, keepdims=True); sd = loads[:, :TRAIN_END].std(1, keepdims=True)
    z = (loads - mu) / sd
    dmax = loads[:, :TRAIN_END].reshape(N_ENT, -1, horizon).max(2)          # block maxima over the horizon length in training
    cap = np.quantile(dmax, 0.8, axis=1)
    # label at hour t: max over (t, t+horizon] > cap  (defined for t <= H_TOT - horizon - 1)
    lab = np.full((N_ENT, H_TOT), np.nan)
    for t in range(H_TOT - horizon):
        lab[:, t] = (loads[:, t + 1:t + horizon + 1].max(1) > cap).astype(float)
    return dict(load=loads, z=z, lab=lab, temp=temp, cap=cap, mu=mu.ravel(), sd=sd.ravel(), meta=meta)


class FEAT(nn.Module):
    """rolling-aggregate-feature MLP: a FIXED linear layer computes block means of the window (the standard engineered rolling
    features of load forecasting): the last 3/6/12/24/48/96/168 hours, and the blocks one day ago that correspond to the next
    6 h and next 12 h (hours t-23..t-18, t-23..t-12) and the block one week ago corresponding to the next 24 h (t-167..t-144);
    then a 10-32-32-1 ReLU MLP + sigmoid.  The whole model is a network on the raw window, so the verifier sees the same series
    perturbation as for 'mlp'."""
    BLOCKS = [(0, 3), (0, 6), (0, 12), (0, 24), (0, 48), (0, 96), (0, 168), (18, 24), (12, 24), (144, 168)]   # (a, b): hours t-b+1 .. t-a

    BLOCKS24 = [(0, 24), (0, 48), (0, 96), (0, 168), (24, 48), (144, 168)]   # 'feat24': day-level blocks only (every block >= 24 h)

    def __init__(self, hdim=32, day_level=False):
        super().__init__()
        if day_level:
            self.BLOCKS = self.BLOCKS24
        Wf = torch.zeros(len(self.BLOCKS), W)
        for i, (a_, b_) in enumerate(self.BLOCKS):
            Wf[i, W - b_:W - a_] = 1.0 / (b_ - a_)
        self.feat = nn.Linear(W, len(self.BLOCKS), bias=False); self.feat.weight.data.copy_(Wf); self.feat.weight.requires_grad_(False)
        self.net = nn.Sequential(nn.Linear(len(self.BLOCKS), hdim), nn.ReLU(), nn.Linear(hdim, hdim), nn.ReLU(), nn.Linear(hdim, 1))

    def logit(self, x):
        return self.net(self.feat(x))

    def forward(self, x):
        return torch.sigmoid(self.logit(x))


class MLP(nn.Module):
    def __init__(self, hdim=64):
        super().__init__()
        self.net = nn.Sequential(nn.Linear(W, hdim), nn.ReLU(), nn.Linear(hdim, hdim), nn.ReLU(), nn.Linear(hdim, 1))

    def logit(self, x):
        return self.net(x)

    def forward(self, x):
        return torch.sigmoid(self.net(x))


class Incr(nn.Module):
    """two-window difference model g_k(z) = F(z[:, k:k+W]) - F(z[:, :W]) on the joint input z of length W + k (shared values)"""
    def __init__(self, F, k):
        super().__init__(); self.F = F; self.k = k

    def forward(self, z):
        return self.F(z[:, self.k:self.k + W]) - self.F(z[:, :W])


def build(name):
    return FEAT(day_level=name.startswith("feat24")) if name.startswith("feat") else MLP()          # suffix "_tc" = same architecture, temporal-consistency training


def horizon(name):
    return 168 if name.endswith("7") else 24


def load_model(name):
    m = build(name); m.load_state_dict(torch.load(os.path.join(OUT, f"model_{name}.pt"), map_location="cpu")); m.eval(); return m


def eval_series(D):
    """z-scored evaluation series per feeder: hours EVAL_START - W + 1 .. H_TOT - 1 (length T + W - 1)"""
    return D["z"][:, EVAL_START - W + 1:H_TOT].astype(np.float32)


def windows(y):
    """y [..., T + W - 1] -> sliding windows [..., T, W]"""
    yt = torch.as_tensor(y)
    return yt.unfold(-1, W, 1)


def jdump(obj, path):
    def conv(o):
        if isinstance(o, (np.floating,)): return float(o)
        if isinstance(o, (np.integer,)): return int(o)
        if isinstance(o, np.ndarray): return o.tolist()
        if isinstance(o, (np.bool_,)): return bool(o)
        raise TypeError(type(o))
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(obj, fh, indent=1, default=conv)
